USE [master]
GO

/****** Object:  Database [WH_Bronze]    Script Date: 06/02/2023 14:56:19 ******/
CREATE DATABASE [WH_Bronze]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bronze', FILENAME = N'F:\Data\BSG\Bronze.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB ), 
 FILEGROUP [Bronze_Default]  DEFAULT
( NAME = N'Bronze_Default', FILENAME = N'F:\Data\BSG\Bronze_Default.ndf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'Bronze_Log', FILENAME = N'G:\Logs\BSG\Bronze.ldf' , SIZE = 1048576KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WH_Bronze].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WH_Bronze] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [WH_Bronze] SET ANSI_NULLS ON 
GO

ALTER DATABASE [WH_Bronze] SET ANSI_PADDING ON 
GO

ALTER DATABASE [WH_Bronze] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [WH_Bronze] SET ARITHABORT ON 
GO

ALTER DATABASE [WH_Bronze] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WH_Bronze] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WH_Bronze] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WH_Bronze] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WH_Bronze] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [WH_Bronze] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [WH_Bronze] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WH_Bronze] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [WH_Bronze] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WH_Bronze] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WH_Bronze] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WH_Bronze] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WH_Bronze] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WH_Bronze] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WH_Bronze] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WH_Bronze] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WH_Bronze] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WH_Bronze] SET RECOVERY FULL 
GO

ALTER DATABASE [WH_Bronze] SET  MULTI_USER 
GO

ALTER DATABASE [WH_Bronze] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WH_Bronze] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WH_Bronze] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WH_Bronze] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WH_Bronze] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WH_Bronze] SET QUERY_STORE = OFF
GO

USE [WH_Bronze]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [WH_Bronze] SET  READ_WRITE 
GO


