USE [master]
GO

/****** Object:  Database [WH_Gold]    Script Date: 06/02/2023 14:58:47 ******/
CREATE DATABASE [WH_Gold]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gold', FILENAME = N'F:\Data\BSG\Gold.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB ), 
 FILEGROUP [Gold_Default]  DEFAULT
( NAME = N'Gold_Default', FILENAME = N'F:\Data\BSG\Gold_Default.ndf' , SIZE = 84934656KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'Gold_Log', FILENAME = N'G:\Logs\BSG\Gold.ldf' , SIZE = 53477376KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WH_Gold].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WH_Gold] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [WH_Gold] SET ANSI_NULLS ON 
GO

ALTER DATABASE [WH_Gold] SET ANSI_PADDING ON 
GO

ALTER DATABASE [WH_Gold] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [WH_Gold] SET ARITHABORT ON 
GO

ALTER DATABASE [WH_Gold] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WH_Gold] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WH_Gold] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WH_Gold] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WH_Gold] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [WH_Gold] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [WH_Gold] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WH_Gold] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [WH_Gold] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WH_Gold] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WH_Gold] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WH_Gold] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WH_Gold] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WH_Gold] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WH_Gold] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WH_Gold] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WH_Gold] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WH_Gold] SET RECOVERY FULL 
GO

ALTER DATABASE [WH_Gold] SET  MULTI_USER 
GO

ALTER DATABASE [WH_Gold] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WH_Gold] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WH_Gold] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WH_Gold] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WH_Gold] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WH_Gold] SET QUERY_STORE = OFF
GO

USE [WH_Gold]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [WH_Gold] SET  READ_WRITE 
GO


