USE [master]
GO

/****** Object:  Database [WH_Silver]    Script Date: 06/02/2023 14:58:28 ******/
CREATE DATABASE [WH_Silver]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Silver', FILENAME = N'F:\Data\BSG\Silver.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB ), 
 FILEGROUP [Silver_Default]  DEFAULT
( NAME = N'Silver_Default', FILENAME = N'F:\Data\BSG\Silver_Default.ndf' , SIZE = 39845888KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
 LOG ON 
( NAME = N'Silver_Log', FILENAME = N'G:\Logs\BSG\Silver.ldf' , SIZE = 68157440KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WH_Silver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WH_Silver] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [WH_Silver] SET ANSI_NULLS ON 
GO

ALTER DATABASE [WH_Silver] SET ANSI_PADDING ON 
GO

ALTER DATABASE [WH_Silver] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [WH_Silver] SET ARITHABORT ON 
GO

ALTER DATABASE [WH_Silver] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WH_Silver] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WH_Silver] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WH_Silver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WH_Silver] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [WH_Silver] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [WH_Silver] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WH_Silver] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [WH_Silver] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WH_Silver] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WH_Silver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WH_Silver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WH_Silver] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WH_Silver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WH_Silver] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WH_Silver] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WH_Silver] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WH_Silver] SET RECOVERY FULL 
GO

ALTER DATABASE [WH_Silver] SET  MULTI_USER 
GO

ALTER DATABASE [WH_Silver] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WH_Silver] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WH_Silver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WH_Silver] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WH_Silver] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WH_Silver] SET QUERY_STORE = OFF
GO

USE [WH_Silver]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [WH_Silver] SET  READ_WRITE 
GO


